from .denseSynapse import DenseSynapse
from .staticSynapse import StaticSynapse
from .STPDenseSynapse import STPDenseSynapse
from .hebbian.hebbianSynapse import HebbianSynapse
from .hebbian.traceSTDPSynapse import TraceSTDPSynapse
from .hebbian.expSTDPSynapse import ExpSTDPSynapse
from .hebbian.eventSTDPSynapse import EventSTDPSynapse
from .hebbian.BCMSynapse import BCMSynapse
from .convolution.convSynapse import ConvSynapse
from .convolution.staticConvSynapse import StaticConvSynapse
from .convolution.hebbianConvSynapse import HebbianConvSynapse
from .convolution.traceSTDPConvSynapse import TraceSTDPConvSynapse
from .convolution.deconvSynapse import DeconvSynapse
from .convolution.staticDeconvSynapse import StaticDeconvSynapse
from .convolution.hebbianDeconvSynapse import HebbianDeconvSynapse
from .convolution.traceSTDPDeconvSynapse import TraceSTDPDeconvSynapse
