name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-name: test
    
    - name: Install dependencies
      run: |
        conda install -n test numpy=1.26 pytest pip
        conda run -n test pip install -e .

    - name: Run tests
      run: |
        conda run -n test pytest
